plugins {
    id 'idea'
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '2.0.141'
}

version = project.version
group = project.group
base { archivesName = 'ancientspellcraft-neoforge' }

java {
    toolchain { languageVersion = JavaLanguageVersion.of(21) }
}

neoForge {
    version = project.neo_version

    parchment {
        minecraftVersion = project.parchment_minecraft
        mappingsVersion = project.parchment_version
    }

    runs {
        client { client() }
        server { server() }
        gameTestServer {
            type = 'gameTestServer'
            systemProperty 'neoforge.enabledGameTestNamespaces', 'ebwizardry'
        }
    }

    mods {
        "${project.mod_id}" { sourceSet sourceSets.main }
    }
}

repositories {
    mavenLocal()
    mavenCentral()
    maven { name = 'Illusive Soulworks'; url = 'https://maven.theillusivec4.top/' }
    maven { name = 'Shedaniel'; url = 'https://maven.shedaniel.me/' }
    maven { name = 'BlameJared'; url = 'https://maven.blamejared.com/' }
}

dependencies {
    compileOnly 'org.jetbrains:annotations:23.0.0'
    implementation "com.koomplo.wizardry:electroblobs-wizardry-redux-neoforge:${project.ebwizardry_version}"
    compileOnly "top.theillusivec4.curios:curios-neoforge:${project.curios_version}:api"
    runtimeOnly "top.theillusivec4.curios:curios-neoforge:${project.curios_version}"
    implementation "com.windanesz.wizardryutils:wizardryutils-neoforge:${project.wizardryutils_version}"
}

processResources {
    var replaceProperties = [
            minecraft_version: minecraft_version,
            neo_version      : neo_version,
            mod_id           : mod_id,
            mod_name         : mod_name,
            mod_license      : license,
            mod_version      : version,
            mod_author       : mod_author,
            mod_description  : description
    ]
    inputs.properties replaceProperties

    filesMatching(['META-INF/neoforge.mods.toml']) {
        expand replaceProperties
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifactId = base.archivesName.get()
            from components.java
        }
    }
    repositories { mavenLocal() }
}
