# Project
version=3.49.0
group=com.windanesz.ancientspellcraft
java_version=21

# Common
minecraft_version=1.21.1
mod_name=Ancient Spellcraft
mod_id=ancientspellcraft
mod_author=WinDanesz
license=Open source; ported and published with permission from WinDanesz
description=Ancient Spellcraft addon for Electroblob's Wizardry. Unofficial NeoForge 1.21.1 port.

# NeoForge
neo_version=21.1.235

# ParchmentMC
parchment_minecraft=1.21.1
parchment_version=2024.11.17

# Dependencies
ebwizardry_version=0.1.27
wizardryutils_version=2.0.0
curios_version=9.5.1+1.21.1

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
